const data = [
    {
        id: 1,
        class_id: 3,
        email: null,
        identity_number: "2122.1.003",
        full_name: "Ajeng Rosalinda",
        username: "ajeng_rosalinda_605",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "p",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 1,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Jangan diulangi lagi ya",
        photo_proof: "foto",
        status: "pending",
        clas: "",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "merokok",
        point: 10,
        deleted_at: null,
    },
    {
        id: 1,
        class_id: 3,
        email: null,
        identity_number: "2122.1.004",
        full_name: "Bagas Tri Mulyono",
        username: "bagas_tri_mulyono_850",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 1,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Pelanggaran ringan di dalam kelas",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "merokok",
        point: 10,
        deleted_at: null,
    },
    {
        id: 1,
        class_id: 3,
        email: null,
        identity_number: "2122.1.007",
        full_name: "Daviansyah Nur Hidayat",
        username: "daviansyah_nur_hidayat_361",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 1,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Mengganggu konsentrasi teman",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "merokok",
        point: 10,
        deleted_at: null,
    },
    {
        id: 1,
        class_id: 3,
        email: null,
        identity_number: "2122.1.011",
        full_name: "Dendi Junaedi",
        username: "dendi_junaedi_418",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 1,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Tidak mengumpulkan tugas",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "merokok",
        point: 10,
        deleted_at: null,
    },
    {
        id: 1,
        class_id: 3,
        email: null,
        identity_number: "2122.1.014",
        full_name: "Fadhul Aziim",
        username: "fadhul_aziim_155",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 1,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Tidak patuh pada peraturan sekolah",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "merokok",
        point: 10,
        deleted_at: null,
    },
    {
        id: 1,
        class_id: 3,
        email: null,
        identity_number: "2122.1.017",
        full_name: "Galih Satria",
        username: "galih_satria_376",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 1,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Merusak fasilitas sekolah",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "merokok",
        point: 10,
        deleted_at: null,
    },
    {
        id: 1,
        class_id: 3,
        email: null,
        identity_number: "2122.1.020",
        full_name: "Ibnu Yusuf Alasfahani",
        username: "ibnu_yusuf_alasfahani_361",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 1,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Berkelompok saat ujian",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "merokok",
        point: 10,
        deleted_at: null,
    },
    {
        id: 1,
        class_id: 3,
        email: null,
        identity_number: "2122.1.023",
        full_name: "Junius Ardiansyah",
        username: "junius_ardiansyah_378",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 1,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Membuat keributan di kantin",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "merokok",
        point: 10,
        deleted_at: null,
    },
    {
        id: 1,
        class_id: 3,
        email: null,
        identity_number: "2122.1.026",
        full_name: "Muhamad Asep Alan Subhani",
        username: "muhamad_asep_alan_subhani_981",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 1,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Terlambat masuk kelas",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "merokok",
        point: 10,
        deleted_at: null,
    },
    {
        id: 1,
        class_id: 3,
        email: null,
        identity_number: "2122.1.030",
        full_name: "Muhamad Raditia Farell",
        username: "muhamad_raditia_farell_485",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 1,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Tidak fokus selama pelajaran",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "merokok",
        point: 10,
        deleted_at: null,
    },
    {
        id: 1,
        class_id: 3,
        email: null,
        identity_number: "2122.1.033",
        full_name: "Muhammad Wahid Kaysan",
        username: "muhammad_wahid_kaysan_609",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 1,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Menggunakan ponsel secara tidak tepat",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "merokok",
        point: 10,
        deleted_at: null,
    },
    {
        id: 1,
        class_id: 3,
        email: null,
        identity_number: "2122.1.036",
        full_name: "Raditya Pratama Sopyan",
        username: "raditya_pratama_sopyan_659",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 1,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Membuang sampah sembarangan",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "merokok",
        point: 10,
        deleted_at: null,
    },
    {
        id: 1,
        class_id: null,
        email: null,
        identity_number: "2122.1.039",
        full_name: "Sivan Ariyanto",
        username: "sivan_ariyanto_924",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 1,
        student_id: 36,
        student_parent_id: null,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Jangan di ulangi lagi yaah",
        photo_proof: null,
        status: "confirm",
        clas: "X TO 3",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "merokok",
        point: 10,
        deleted_at: null,
    },
    {
        id: 1,
        class_id: null,
        email: null,
        identity_number: "2122.1.069",
        full_name: "Muhamad Ridwan Al Ghozali",
        username: "muhamad_ridwan_al_ghozali_466",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 1,
        student_id: 36,
        student_parent_id: null,
        report_by: "admin",
        teacher_id: null,
        admin_id: 1,
        report_at: null,
        note: "asd",
        photo_proof: null,
        status: "confirm",
        clas: "X TO 3",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "merokok",
        point: 10,
        deleted_at: null,
    },
    {
        id: 1,
        class_id: null,
        email: null,
        identity_number: "2122.1.070",
        full_name: "Muhamad Rijki Agustian",
        username: "muhamad_rijki_agustian_875",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 1,
        student_id: 36,
        student_parent_id: null,
        report_by: "admin",
        teacher_id: null,
        admin_id: 1,
        report_at: null,
        note: "asd",
        photo_proof: null,
        status: "confirm",
        clas: "X TO 3",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "merokok",
        point: 10,
        deleted_at: null,
    },
    {
        id: 1,
        class_id: null,
        email: null,
        identity_number: "2122.1.071",
        full_name: "Muhamad Sofian Ilham Zhetia",
        username: "muhamad_sofian_ilham_zhetia_939",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 1,
        student_id: 36,
        student_parent_id: null,
        report_by: "admin",
        teacher_id: null,
        admin_id: 1,
        report_at: null,
        note: "testing",
        photo_proof: null,
        status: "confirm",
        clas: "X TO 3",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "merokok",
        point: 10,
        deleted_at: null,
    },
    {
        id: 1,
        class_id: null,
        email: null,
        identity_number: "2122.1.074",
        full_name: "Naufal Dzakwan Abdillah",
        username: "naufal_dzakwan_abdillah_137",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 1,
        student_id: 2120,
        student_parent_id: null,
        report_by: "admin",
        teacher_id: null,
        admin_id: 1,
        report_at: null,
        note: "Jangan pernah merokok di warung",
        photo_proof: null,
        status: "confirm",
        clas: "XII RPL",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "merokok",
        point: 10,
        deleted_at: null,
    },
    {
        id: 2,
        class_id: 3,
        email: null,
        identity_number: "2122.1.001",
        full_name: "Abdul Pida Ismail",
        username: "abdul_pida_ismail_497",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 2,
        student_id: 36,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Jangan diulangi lagi ya",
        photo_proof: "foto",
        status: "pending",
        clas: "",
        jenis_pelanggaran: "pelanggaran berat",
        name: "tawuran",
        point: 30,
        deleted_at: null,
    },
    {
        id: 2,
        class_id: 3,
        email: null,
        identity_number: "2122.1.002",
        full_name: "Aditiya Pasya",
        username: "aditiya_pasya_344",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 2,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Jangan diulangi lagi ya",
        photo_proof: "foto",
        status: "pending",
        clas: "",
        jenis_pelanggaran: "pelanggaran berat",
        name: "tawuran",
        point: 30,
        deleted_at: null,
    },
    {
        id: 2,
        class_id: 3,
        email: null,
        identity_number: "2122.1.005",
        full_name: "Bagis Riyadi",
        username: "bagis_riyadi_283",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 2,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Keterlambatan masuk kelas",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran berat",
        name: "tawuran",
        point: 30,
        deleted_at: null,
    },
    {
        id: 2,
        class_id: 3,
        email: null,
        identity_number: "2122.1.009",
        full_name: "Dede Ipah",
        username: "dede_ipah_903",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 2,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Membuang sampah sembarangan",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran berat",
        name: "tawuran",
        point: 30,
        deleted_at: null,
    },
    {
        id: 2,
        class_id: 3,
        email: null,
        identity_number: "2122.1.012",
        full_name: "Elga Ikhwan Pratama",
        username: "elga_ikhwan_pratama_585",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 2,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Berkelahi dengan teman",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran berat",
        name: "tawuran",
        point: 30,
        deleted_at: null,
    },
    {
        id: 2,
        class_id: 3,
        email: null,
        identity_number: "2122.1.015",
        full_name: "Fadli Adam",
        username: "fadli_adam_242",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 2,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Mengganggu ketertiban kelas",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran berat",
        name: "tawuran",
        point: 30,
        deleted_at: null,
    },
    {
        id: 2,
        class_id: 3,
        email: null,
        identity_number: "2122.1.018",
        full_name: "Hamdani Maulana",
        username: "hamdani_maulana_518",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 2,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Tidak hadir saat kegiatan kelas",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran berat",
        name: "tawuran",
        point: 30,
        deleted_at: null,
    },
    {
        id: 2,
        class_id: 3,
        email: null,
        identity_number: "2122.1.021",
        full_name: "Ine Meylina",
        username: "ine_meylina_137",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "p",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 2,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Menyontek saat ujian",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran berat",
        name: "tawuran",
        point: 30,
        deleted_at: null,
    },
    {
        id: 2,
        class_id: 3,
        email: null,
        identity_number: "2122.1.024",
        full_name: "Mohammad Farrel Kusuma Wardhana",
        username: "mohammad_farrel_kusuma_wardhana_259",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 2,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Mencontek saat ulangan",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran berat",
        name: "tawuran",
        point: 30,
        deleted_at: null,
    },
    {
        id: 2,
        class_id: 3,
        email: null,
        identity_number: "2122.1.027",
        full_name: "Muhamad Fawwaz",
        username: "muhamad_fawwaz_449",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 2,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Tidak membawa buku catatan",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran berat",
        name: "tawuran",
        point: 30,
        deleted_at: null,
    },
    {
        id: 2,
        class_id: 3,
        email: null,
        identity_number: "2122.1.031",
        full_name: "Muhamad Randi Fazry",
        username: "muhamad_randi_fazry_127",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 2,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Membuat kebisingan di kelas",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran berat",
        name: "tawuran",
        point: 30,
        deleted_at: null,
    },
    {
        id: 2,
        class_id: 3,
        email: null,
        identity_number: "2122.1.034",
        full_name: "Nasrulloh Awalludin",
        username: "nasrulloh_awalludin_329",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 2,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Tidak patuh pada aturan sekolah",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran berat",
        name: "tawuran",
        point: 30,
        deleted_at: null,
    },
    {
        id: 2,
        class_id: null,
        email: null,
        identity_number: "2122.1.040",
        full_name: "Tasya Muhamad Rizky",
        username: "tasya_muhamad_rizky_644",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 2,
        student_id: 36,
        student_parent_id: null,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Tawuran adalah perbuatan yang keji !",
        photo_proof: null,
        status: "confirm",
        clas: "X TO 3",
        jenis_pelanggaran: "pelanggaran berat",
        name: "tawuran",
        point: 30,
        deleted_at: null,
    },
    {
        id: 2,
        class_id: null,
        email: null,
        identity_number: "2122.1.072",
        full_name: "Muhammad Abdul Majid Hermawan",
        username: "muhammad_abdul_majid_hermawan_144",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 2,
        student_id: 36,
        student_parent_id: null,
        report_by: "admin",
        teacher_id: null,
        admin_id: 1,
        report_at: null,
        note: "asd",
        photo_proof: null,
        status: "confirm",
        clas: "X TO 3",
        jenis_pelanggaran: "pelanggaran berat",
        name: "tawuran",
        point: 30,
        deleted_at: null,
    },
    {
        id: 3,
        class_id: 3,
        email: null,
        identity_number: "2122.1.006",
        full_name: "Daniel Maulana",
        username: "daniel_maulana_999",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 3,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Tidak membawa buku pelajaran",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "bolos sekolah",
        point: 5,
        deleted_at: null,
    },
    {
        id: 3,
        class_id: 3,
        email: null,
        identity_number: "2122.1.010",
        full_name: "Dedeh Winingsih",
        username: "dedeh_winingsih_210",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 3,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Menggunakan ponsel di kelas",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "bolos sekolah",
        point: 5,
        deleted_at: null,
    },
    {
        id: 3,
        class_id: 3,
        email: null,
        identity_number: "2122.1.013",
        full_name: "Fachry Rahmad Hidayat Nazara",
        username: "fachry_rahmad_hidayat_nazara_581",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 3,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Melanggar aturan berpakaian",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "bolos sekolah",
        point: 5,
        deleted_at: null,
    },
    {
        id: 3,
        class_id: 3,
        email: null,
        identity_number: "2122.1.016",
        full_name: "Fadli Muhammad",
        username: "fadli_muhammad_932",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 3,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Meninggalkan kelas tanpa izin",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "bolos sekolah",
        point: 5,
        deleted_at: null,
    },
    {
        id: 3,
        class_id: 3,
        email: null,
        identity_number: "2122.1.019",
        full_name: "Hasbi Abdul Basit",
        username: "hasbi_abdul_basit_451",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 3,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Tidak menghormati guru",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "bolos sekolah",
        point: 5,
        deleted_at: null,
    },
    {
        id: 3,
        class_id: 3,
        email: null,
        identity_number: "2122.1.022",
        full_name: "Jaya Mulyani",
        username: "jaya_mulyani_943",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 3,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Tidak menghormati petugas sekolah",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "bolos sekolah",
        point: 5,
        deleted_at: null,
    },
    {
        id: 3,
        class_id: 3,
        email: null,
        identity_number: "2122.1.025",
        full_name: "Moreno Fairuzi",
        username: "moreno_fairuzi_131",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 3,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Tidak mengikuti aturan kebersihan",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "bolos sekolah",
        point: 5,
        deleted_at: null,
    },
    {
        id: 3,
        class_id: 3,
        email: null,
        identity_number: "2122.1.029",
        full_name: "Muhamad Pandu Wibisono",
        username: "muhamad_pandu_wibisono_855",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 3,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Mengganggu teman sekelas",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "bolos sekolah",
        point: 5,
        deleted_at: null,
    },
    {
        id: 3,
        class_id: 3,
        email: null,
        identity_number: "2122.1.032",
        full_name: "Muhamad Zidan Nurpuadin",
        username: "muhamad_zidan_nurpuadin_450",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 3,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Tidak mengikuti instruksi guru",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "bolos sekolah",
        point: 5,
        deleted_at: null,
    },
    {
        id: 3,
        class_id: 3,
        email: null,
        identity_number: "2122.1.035",
        full_name: "Raden Zakwinta Santana",
        username: "raden_zakwinta_santana_703",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 3,
        student_id: 38,
        student_parent_id: 1,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "Melanggar tata tertib kelas",
        photo_proof: "foto",
        status: "confirm",
        clas: "",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "bolos sekolah",
        point: 5,
        deleted_at: null,
    },
    {
        id: 3,
        class_id: null,
        email: null,
        identity_number: "2122.1.041",
        full_name: "Wijaya",
        username: "wijaya_640",
        password:
            "$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
        gender: "l",
        address: null,
        phone_number: null,
        remember_token: null,
        is_active: 1,
        created_at: "2023-10-27 13:53:12",
        updated_at: "2023-10-27 13:53:12",
        violation_category_id: 3,
        student_id: 38,
        student_parent_id: null,
        report_by: "teacher",
        teacher_id: null,
        admin_id: null,
        report_at: null,
        note: "jangan di ulangi yah",
        photo_proof: null,
        status: "confirm",
        clas: "X TO 3",
        jenis_pelanggaran: "pelanggaran ringan",
        name: "bolos sekolah",
        point: 5,
        deleted_at: null,
    },
];

console.log(data.length);
